In [1]:
#Mounting Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
#Importing LIbraries
import numpy as np
import torch.nn.functional as F
import torch
import torch.nn as nn
from collections import OrderedDict
import torch.optim as optim
import cv2
import os
import pandas as pd
from collections import Counter
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import glob
import pickle
import warnings
import sys
warnings.filterwarnings("ignore")
os.system('CUDA_LAUNCH_BLOCKING=1')

use_cuda = torch.cuda.is_available()
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
device_ids = [i for i in range(torch.cuda.device_count())]
device = 'cuda' if use_cuda else 'cpu'
torch.backends.cudnn.benchmark = True

In [3]:
path_to_code='/content/drive/MyDrive/Crack/'
path_to_data='/content/drive/MyDrive/localdir/'
path_to_save_checkpoints="/content/drive/MyDrive/Crack/Demo/"

In [4]:
sys.path.append(path_to_code)
from models import UNet,Crack_UNet
from data import CustomDataset
from losses import Loss
from model_initializer import Initializer
from train import Train

In [5]:
dataset = CustomDataset(path_to_data+"training/")
print(dataset.__len__())
trainloader = DataLoader(dataset, batch_size=4, shuffle=False)

dataset = CustomDataset(path_to_data+"validation/")
valloader = DataLoader(dataset, batch_size=4, shuffle=False)
print(dataset.__len__())



2286
77


In [6]:
NUM_EPOCHS=100
LEARNING_RATE=0.01

#Model we ewant to run
model=Crack_UNet()

#Weight given to dice loss
w_d=0.95

#Weight given to BCE loss
w_b=0.05

#Weight given to weighted BCE loss
w_wb=0

#Weights of class 1 in weighted BCE loss
weight=10

loss_=Loss()
model_intialize=Initializer (path_to_save_checkpoints,model,LEARNING_RATE)
train=Train(path_to_save_checkpoints,NUM_EPOCHS,LEARNING_RATE,w_d,w_b,w_wb,weight)


best_checkpoint_file,checkpoint_file, network, optimizer, train_losses, test_losses,train_accuracies,test_accuracies,best_score =model_intialize.initialise_model()

train_losses, test_losses,train_accuracies,test_accuracies = train.train_model(best_checkpoint_file,checkpoint_file, network, optimizer, valloader, trainloader,train_losses, test_losses,train_accuracies,test_accuracies,best_score )

Initialised Network, Optimizer and Loss
No previous checkpoints exist, initialising network from start...
______________________________________________________________________________
epoch: 1 Train loss :  0.9270790356397629
-Train accuracy: 0.9528059959411621
Dice Ratio :  [0.97580914 0.0387727 ]
[[99809144  4132188]
 [  816462    99806]]

Validation Accuracy: 0.9891811222225041
Dice Ratio :  [0.99456104 0.00331346]
[[19966345   135075]
 [   83305      363]]
______________________________________________________________________________
epoch: 2 Train loss :  0.9227024865150452
-Train accuracy: 0.959475736618042
Dice Ratio :  [0.97929704 0.0484065 ]
[[100500245   3441087]
 [   808190    108078]]

Validation Accuracy: 0.9673844374619521
Dice Ratio :  [0.98342131 0.00200706]
[[19526078   575342]
 [   83006      662]]
______________________________________________________________________________
epoch: 3 Train loss :  0.9217036819458008
-Train accuracy: 0.9609282875061035
Dice Ratio :  

KeyboardInterrupt: ignored